name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: UV Sync
        run: uv sync --frozen
      - name: install pre-commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
      - name: pre-commit
        run: pre-commit run --all-files
      - name: Test
        run: uv run --frozen pytest
